version: '3.8'
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tikit_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: steve
      POSTGRES_DB: tikit_dev
    ports:
      - '5432:5432'
    volumes:
      - tikit_pgdata:/var/lib/postgresql/data

volumes:
  tikit_pgdata:
