[build]
builder = "nixpacks"
buildCommand = "pnpm run build"

[deploy]
startCommand = "pnpm run start:prod"
releaseCommand = "pnpm prisma migrate deploy"
healthcheckPath = "/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
