-- AlterTable Event
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "placeId" TEXT;

-- AlterTable TicketType
ALTER TABLE "TicketType" ADD COLUMN IF NOT EXISTS "salesStartsAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "salesEndsAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "trackQuantity" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'available',
ADD COLUMN IF NOT EXISTS "label" TEXT;
